language: node_js
node_js:
  - 'node' # use latest stable nodejs version
before_script:
  - npm install
script:
  - npm run build # jest test with coverage flag does coverage too
after_success:
  - npm run semantic-release
